---
- name: Deploy PostgreSQL Cluster with Pgpool2
  hosts: postgres_cluster
  remote_user: root
  become: true
  become_method: sudo
  any_errors_fatal: true
  gather_facts: true

  roles:
    - role: firewall
    - role: postgresql-pgpool

  tasks:
    - import_tasks: roles/postgresql-pgpool/tasks/deploy_verification.yml
      tags: [ cluster_info, cluster_status ]
