---
- name: Deploy PostgreSQL Cluster with Pgpool2
  hosts: postgres_cluster
  remote_user: root
  become: true
  become_method: sudo
  any_errors_fatal: true
  gather_facts: true

  tasks:
    - name: Copy SSH key to cluster nodes
      ansible.builtin.ansible.posix.authorized_key:
        user: root
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        state: present
      with_items:
        - node1
        - node2
        - node3

    - block:
        - name: Apply firewall role
          include_role:
            name: firewall

        - name: Apply PostgreSQL-Pgpool role
          include_role:
            name: postgresql-pgpool

    - name: Import tasks for deploy verification
      import_tasks: roles/postgresql-pgpool/tasks/deploy_verification.yml
      tags: [cluster_info, cluster_status]
