---
# Vars for RedHat based distributions



# PostgreSQL vars for RedHat based distributions
#
# Using a different cluster name could cause problems with SELinux.

# See /usr/lib/systemd/system/postgresql-*.service
#postgresql_cluster_name: "data"
#postgresql_service_name: "postgresql-{{ postgresql_version }}"

#postgresql_varlib_directory_name: "pgsql"

# Used to execute initdb
#postgresql_bin_directory: "/usr/pgsql-{{postgresql_version}}/bin"

#postgresql_unix_socket_directories:
#  - "{{ postgresql_pid_directory }}"
#  - /tmp

#postgresql_fdw_mysql_packages: "mysql_fdw_{{ postgresql_version_terse }}"
#postgresql_fdw_ogr_packages: "ogr_fdw{{ postgresql_version_terse }}"




# PostgreSQL variables
postgresql_cluster_name: "data"
postgresql_home_dir: "/var/lib/pgsql"
postgresql_install_backup_dir: "{{ postgresql_home_dir }}/install_backup"
postgresql_data_dir: "{{ postgresql_home_dir }}/{{ postgresql_version }}/{{ postgresql_cluster_name }}"
postgresql_conf_dir: "{{ postgresql_data_dir }}"
postgresql_archive_dir: "{{ postgresql_home_dir }}/archivedir"
postgresql_bin_parent_dir: "/usr/pgsql-{{ postgresql_version }}"
postgresql_bin_dir: "{{ postgresql_bin_parent_dir }}/bin"
postgresql_log_dir: "/var/log/postgresql"
postgresql_unix_socket_dir: "/var/run/postgresql"
postgresql_pgpass: "{{ postgresql_home_dir }}/.pgpass"

postgresql_version_terse: "{{ postgresql_version | replace('.', '') }}"

pgpool_conf_dir: "/etc/pgpool-II"
pgpool_log_dir: "/var/log/pgpool-II"
pgpool_bin_dir: "/usr/bin"
pgpool_wd_ipc_socket_dir: "/tmp"
pgpool_socket_dir: "/tmp"
pgpool_pcp_socket_dir: "/tmp"




# Repository (optional)
yum_repository: []
#  - name: "repo name"
#    description: "repo description"
#    baseurl: "https://repo.url"
#    gpgkey: "https://key.url"
#    gpgcheck: "yes"

install_epel_repo: 'true'
install_postgresql_repo: 'true' # postgresql repository will be installed from the package "pgdg-redhat-repo-latest.noarch.rpm" (tasks/add-repository.yml)
install_pgpool2_repo: 'true'

# Packages
system_packages:
  - rsync
  - sudo
  - vim
  - curl
  - less
  - python
  - python-devel
  - python-psycopg2
  - python-setuptools
  - python36
  - python36-devel
  - gcc
  - unzip
  - gzip
  - jq
  - iptables
  - acl
  - iproute
  - rsyslog

postgresql_packages:
  - postgresql{{ postgresql_version_terse }}
  - postgresql{{ postgresql_version_terse }}-server
  - postgresql{{ postgresql_version_terse }}-contrib
  - postgresql{{ postgresql_version_terse }}-devel
  - postgresql{{ postgresql_version_terse }}-libs  
  - pgcryptokey{{ postgresql_version_terse }}
#  - pg_repack{{ postgresql_version_terse }}

pgpool_packages:
  - pgpool-II-pg{{ postgresql_version_terse }}
  - pgpool-II-pg{{ postgresql_version_terse }}-debuginfo
  - pgpool-II-pg{{ postgresql_version_terse }}-devel
  - pgpool-II-pg{{ postgresql_version_terse }}-extensions