# System variables
ntp_enabled: 'true' # specify 'true' if you want to install and configure the ntp service
ntp_servers: []
#  - "10.128.64.44"
#  - "10.128.64.45"

timezone: "Asia/Shanghai"
#timezone: "Europe/Moscow"

locales:
  - { language_country: "en_US", encoding: "UTF-8" }
  - { language_country: "zh_CN", encoding: "UTF-8" }
#  - { language_country: "", encoding: "" }


# Kernel parameters
 # these parameters for example! Specify kernel options for your system
sysctl_conf:
  - { name: "vm.swappiness",                  value: "1"         }
  - { name: "vm.min_free_kbytes",             value: "102400"    }
  - { name: "vm.dirty_expire_centisecs",      value: "1000"      }
  - { name: "vm.dirty_background_bytes",      value: "67108864"  }
  - { name: "vm.dirty_bytes",                 value: "536870912" }
#  - { name: "vm.nr_hugepages",                value: "9510"      } # example "9510"=18GB
  - { name: "vm.zone_reclaim_mode",           value: "0"         }
  - { name: "kernel.numa_balancing",          value: "0"         }
  - { name: "kernel.sched_migration_cost_ns", value: "5000000"   }
  - { name: "kernel.sched_autogroup_enabled", value: "0"         }
  - { name: "net.ipv4.ip_nonlocal_bind",      value: "1"         }
  - { name: "net.ipv4.ip_forward",            value: "1"         }
  - { name: "net.ipv4.ip_local_port_range",   value: "1024 65535" }
  - { name: "net.netfilter.nf_conntrack_max", value: "1048576"    }
#  - { name: "",            value: "" }
#  - { name: "",            value: "" }


# Transparent Huge Pages
disable_thp: 'true' # or 'false'


# Max open file limit
set_limits: 'true' # or 'false'
limits_user: "postgres"
soft_nofile: 65536
hard_nofile: 200000


# I/O Scheduler
set_scheduler: 'false' # or 'true'
scheduler:
  - { sched: "deadline" , nr_requests: "1024", device: "sda" }
#  - { sched: "noop" , nr_requests: "1024", device: "sdb" }
#  - { sched: "" , nr_requests: "1024", device: "" }

# Non-multiqueue I/O schedulers:
  # cfq         - for desktop systems and slow SATA drives
  # deadline    - for SAS drives (recommended for databases)
  # noop        - for SSD drives
# Multiqueue I/O schedulers (blk-mq):
## (Recommend the use of blk-mq in environments that support it. For Fast SSD Storage and Linux kernel 4.12+)
  # mq-deadline - (recommended for databases)
  # none        - (ideal for fast random I/O devices such as NVMe)
  # bfq         - (avoid for databases)
  # kyber


# SSH Keys
enable_SSH_Key_based_authentication: 'true' # or 'false'
ssh_keyfile_name: "id_rsa_pgpool"
ssh_postgres_keyfile: "{{ postgresql_home_dir }}/.ssh/{{ ssh_keyfile_name }}"
ssh_key_state: "present"
ssh_known_hosts: "{{ groups['postgres_cluster'] }}"