---
# Create Database
- block:
    - name: PostgreSQL databases | make sure the PostgreSQL databases "{{postgresql_replication_database}}" are present
      become: yes
      become_user: postgres
      postgresql_db:
        name: "{{postgresql_replication_database}}"
        owner: "{{ postgresql_replication_username }}"
        encoding: "{{ postgresql_encoding }}"
        lc_collate: "{{ postgresql_locale }}"
        lc_ctype: "{{ postgresql_locale }}"
        login_unix_socket: "{{ postgresql_unix_socket_dir }}"
        port: "{{ postgresql_port }}"
        #        template: "template0"
        state: present
      ignore_errors: no

    - name: PostgreSQL | databases | make sure the PostgreSQL databases are present
      become: yes
      become_user: postgres
      postgresql_db:
        name: "{{ item.db }}"
        owner: "{{ item.owner }}"
        encoding: "{{ item.encoding }}"
        lc_collate: "{{ item.lc_collate }}"
        lc_ctype: "{{ item.lc_ctype }}"
        login_unix_socket: "{{ postgresql_unix_socket_dir }}"
        port: "{{ postgresql_port }}"
        template: "template0"
        state: present
      ignore_errors: yes
      loop: "{{ postgresql_databases | flatten(1) }}"
      when: postgresql_databases is defined and postgresql_databases | length > 0

  when: is_master == "true"
  tags: [ postgresql, createdb ]