---
# Install PostgreSQL
- name: Install | PostgreSQL packages
  package:
    name: "{{ item }}"
  loop: "{{ postgresql_packages }}"
  environment: '{{ proxy_env | default({}) }}'
  when: postgresql_exists != "true"
  tags: install_postgres