---
# RedHat CentOS
- block:
    - name: Add repository
      yum_repository:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        baseurl: "{{ item.baseurl }}"
        gpgkey: "{{ item.gpgkey }}"
        gpgcheck: "{{ item.gpgcheck }}"
      loop: "{{ yum_repository | flatten(1) }}"
      when: yum_repository | length > 0

    # Install Epel Repository
    - name: "install | get epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
      get_url:
        url: "http://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
        dest: /tmp/
        timeout: 30
        validate_certs: no
      when: install_epel_repo == "true"
      tags: install_epel_repo

    - name: install | EPEL repository
      package:
        name: "/tmp/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
      when: install_epel_repo == "true"
      tags: install_epel_repo

    # Install PostgreSQL Repository
    - name: install | get pgdg-redhat-repo-latest.noarch.rpm
      get_url:
        url: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_distribution_major_version }}-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
        dest: /tmp/
        timeout: 30
        validate_certs: no
      when: install_postgresql_repo == "true"
      tags: install_postgresql_repo

    - name: install | PostgreSQL repository
      package:
        name: /tmp/pgdg-redhat-repo-latest.noarch.rpm
        state: present
      when: install_postgresql_repo == "true"
      tags: install_postgresql_repo

    # Install  pgpool2 Repository
    - name: install | get pgpool2 public RPM yum repository
      get_url:
        url: "http://www.pgpool.net/yum/rpms/4.1/redhat/rhel-7-x86_64/pgpool-II-release-4.1-1.noarch.rpm"
        dest: /tmp/
        timeout: 30
        validate_certs: no
      when: install_pgpool2_repo == "true"
      tags: install_pgpool2_repo

    - name: install | repmgr repository
      package:
        name: /tmp/pgpool-II-release-4.1-1.noarch.rpm
        state: present
      when: install_pgpool2_repo == "true"
      tags: install_pgpool2_repo
  environment: '{{ proxy_env | default({}) }}'
  when: ansible_os_family == "RedHat"
  tags: add_repo